id: I78358C44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:47:39+00:00'
last_modified: '2022-06-07T17:18:24.006994+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD83963
  title: བདེ་སྨོན་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    407F:
      image_group_id: I1PD83979
      title: ''
      total_pages: 372
      order: 1
      base_file: 407F.txt
    55DF:
      image_group_id: I1PD83980
      title: ''
      total_pages: 454
      order: 2
      base_file: 55DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
