id: P003063
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD83963
  title: བདེ་སྨོན་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    374d128790df4126a35dd8b7da281b6e:
      image_group_id: I1PD83979
      title: ''
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
    67e437b25362494db83e81abcd3c5e88:
      image_group_id: I1PD83980
      title: ''
      volume_number: 2
      total_pages: 454
      base_file: v002.txt
